name: PR deploy preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build site
        run: |
          npm ci
          npm run build --if-present
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: "./build"
          production-branch: master
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.event.pull_request.title }}
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: false
          alias: deploy-preview-${{ github.event.number }}
          # netlify-config-path: ./netlify.toml
          # functions-dir: ./functions
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
